### ISSUE TITLE
Does this supercede ARK?

### ISSUE THREAD

**Issue by RandyGaul** [r-lyeh/FWK#2]
Question in title :)

**Comment by r-lyeh** [comment]
AVA, right? ARC is a compression suite! :D

Assuming you meant AVA, this is a tough question that I do not know even how to answer :D To give a recap of my roadmap:
- I have been working in AVA2 since long time ago, as I was never fond of the AVA1 architecture. Main change is basically rewriting lots of stuff and splitting AVA2 into four different repos that live indepently from each other: FWK for the HAL abstractions, CORE for VM/ECS client/server replication model, EVE for a generic 3D editor and IVY for a generic asset pipeline.
- That being said, I want to finish FWK and consider it final (or stable) within the next month. No feature creep here.
- Then, I want to create the EVE & IVY repos, so FWK users can have a generic 3D editor and a pipeline if needed. No feature creep here either.
- Then, I want to continue working on CORE and its VM/Networking replication model until it is stable enough. This is a lab thing and will take me ages to deliver.
- After all that, I'll rewrite from scratch AVA to use FWK for abstraction layers, CORE for ECS/VM client/server replication model, and EVE & IVY for the tooling. This will be fast.
- After that point I think I'll be able to call it AVA2, and start extending that repo into a feature creep beast: PBR, Networking, Blueprints, etc. This will take me forever.

If I just fail bringing AVA2 to life, at least I will have released FWK+EVE+IVY+CORE into stable forms for everybody else to use, or to build stronger foundations with in the future. 

Hope that clears my convoluted plans :D

**Comment by RandyGaul** [comment]
Oh how embarrassing, yes I meant AVA :) My apologies, I wrote that right after waking up and all groggy...

Okay so the rough seems to be that you worked in AVA, and then decided to split it into smaller pieces that you can call "finished", by scoping each one rigidly. Once done then reimplement AVA with the smaller pieces?

You plan is actually the exact same I've been personally doing. My "scoped" pieces are my cute headers, and am now working on the larger thing that integrates them all together. And it's taking ages :P

Thanks for answering! I'll be silently lurking here as you push commits...

**Comment by r-lyeh** [comment]
@RandyGaul I'm happy to say that current version of FWK supersedes any AVA+EVE+IVY combination at a fraction of the size and complexity. Only concern is that editor is a stub, and the whole FWK API is not locked yet and I change it like daily; major bummer for potential users :P

- Next immediate steps include shadowmapping (per @procedural's request), extending asset pipeline, file/vfs optimizations, fixing leaks, crashes and stability issues. 
- Then lock API and release first stable version (I'll stop brute-forcing every commit at this point). 
- Mid-term plans are editor + scene. I plan to have something functional that reads/writes jsons and it is not overengineered.
- Long-term plans adding PBR/IBL (from Foxotron), then lots of extra work in the animation field. Then some more ideas for networking (I have a protoype with networking/replication support already).
